name: ARDphoto
favicon: null
layout_spectrum: 0.2103344656061381
typography_spectrum: 0.521641299361363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b7c4d7'
    - '#788dad'
    - '#325279'
    - '#003b6d'
  brandStrength: 0.9308727032039315
  lightness: 0.7945699754636735
  saturation: 0.5
  rhythmicContrast: 0.3982061087153852
purpose: []
