name: allan rosen-ducat
favicon: null
layout_spectrum: 0
typography_spectrum: 0.521641299361363
title: A few seconds of time.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffece1'
    - '#000000'
    - '#b38529'
    - '#403007'
    - '#dfab7b'
  brandStrength: 0.9375
  lightness: 0.7945699754636735
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
