name: allan rosen-ducat
favicon: null
layout_spectrum: 0
typography_spectrum: 0.521641299361363
title: A few seconds of time.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdd836'
    - '#011601'
    - '#3d5614'
    - '#b85c1c'
    - '#702111'
  brandStrength: 0.5
  lightness: 0.7945699754636735
  saturation: 0.5
  rhythmicContrast: 0.3982061087153852
purpose: []
